src/Entity/Sorties.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SortiesRepository")
 */
class Sorties
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\Length(min="2" , max="30",
     *     minMessage="2 caractères minimum SVP!!",
     *     maxMessage="30 caractères maximun SVP!!")
     */
    private $nom_sortie;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @var string A "d-m-Y H:i:s" formatted value
     * @Assert\GreaterThanOrEqual("today", message ="Veuillez indiquer une date postérieure ou égale à aujourd'hui.")
     *
     */
    private $datedebut;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @var string A "d-m-Y H:i:s" formatted value
     * @Assert\GreaterThan("today", message ="Veuillez indiquer une date postérieure à aujourd'hui.")
     * @Assert\LessThan(propertyPath="datedebut" ,message =" Veuillez indiquer une date antérieure à la date de début.")
     */
    private $datecloture;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(value = 2, message = " La sortie doit avoir au moins 2 participants.")
     */
    private $nbinscriptionsmax;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     * @Assert\Length(max="500", maxMessage=" La description comporte trop de caractères, veuillez réduire.")
     */
    private $descriptionsinfos;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Choice({"Créée", "Ouverte", "Clôturée", "Activité en cours", "Passée", "Annulée"})
     */
    private $etatsortie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sites")
     */
    private $site;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etat")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieux")
     */
    private $lieu;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Participants", mappedBy="sorties")
     */
    private $participants;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Participants")
     */
    private $organisateur;

    /**
     * @return mixed
     */
    public function getOrganisateur()
    {
        return $this->organisateur;
    }

    /**
     * @param mixed $organisateur
     * @return Sorties
     */
    public function setOrganisateur($organisateur)
    {
        $this->organisateur = $organisateur;
        return $this;
    }

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getLieu()
    {
        return $this->lieu;
    }

    /**
     * @param mixed $lieu
     */
    public function setLieu($lieu)
    {
        $this->lieu = $lieu;
    }

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;
    }

    /**
     * @return mixed
     */
    public function getSite()
    {
        return $this->site;
    }

    /**
     * @param mixed $site
     */
    public function setSite($site)
    {
        $this->site = $site;
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNomSortie(): ?string
    {
        return $this->nom_sortie;
    }

    public function setNomSortie(string $nom_sortie): self
    {
        $this->nom_sortie = $nom_sortie;

        return $this;
    }

    public function getDatedebut(): ?\DateTimeInterface
    {
        return $this->datedebut;
    }

    public function setDatedebut(\DateTimeInterface $datedebut): self
    {
        $this->datedebut = $datedebut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDatecloture(): ?\DateTimeInterface
    {
        return $this->datecloture;
    }

    public function setDatecloture(\DateTimeInterface $datecloture): self
    {
        $this->datecloture = $datecloture;

        return $this;
    }

    public function getNbinscriptionsmax(): ?int
    {
        return $this->nbinscriptionsmax;
    }

    public function setNbinscriptionsmax(int $nbinscriptionsmax): self
    {
        $this->nbinscriptionsmax = $nbinscriptionsmax;

        return $this;
    }

    public function getDescriptionsinfos(): ?string
    {
        return $this->descriptionsinfos;
    }

    public function setDescriptionsinfos(?string $descriptionsinfos): self
    {
        $this->descriptionsinfos = $descriptionsinfos;

        return $this;
    }

    public function getEtatsortie(): ?int
    {
        return $this->etatsortie;
    }

    public function setEtatsortie(?int $etatsortie): self
    {
        $this->etatsortie = $etatsortie;

        return $this;
    }

    /**
     * @return Collection|Participants[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participants $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->addSorty($this);
        }

        return $this;
    }

    public function removeParticipant(Participants $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            $participant->removeSorty($this);
        }

        return $this;
    }
}

src/Form/SortiesType.php
<?php

namespace App\Form;

use App\Entity\Sites;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SortiesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('site', EntityType::class, [
                'class' => Sites::class,
                'choice_label' => 'nom_site',
                'label'=>'Site : ',

            ])
            ->add('nom_sortie', TextType::class, ['label' => 'Le nom de la sortie contient : ',
                'required'=>false
            ])
            ->add('entreDate', DateType::class, ['label' => 'Entre ',
                'required'=>false,
                'format'=>'dd MM yyyy',
                'placeholder'=>[
                    'year' => 'Année', 'month' => 'Mois', 'day' => 'Jour',
                ]
            ])
            ->add('etDate', DateType::class, ['label' => 'et ',
                'required'=>false,
                'format'=>'dd MM yyyy',
                'placeholder'=>[
                    'year' => 'Année', 'month' => 'Mois', 'day' => 'Jour',
                    ]
            ])
            ->add('organisateur', CheckboxType::class, ['label' => 'Sorties dont je suis l\'organisateur/trice',
                'required'=>false
            ])
            ->add('inscrit', CheckboxType::class, ['label' => 'Sorties auxquelles je suis inscrit/e',
                'required'=>false
            ])
            ->add('nonInscrit', CheckboxType::class, ['label' => 'Sorties auxquelles je ne suis pas inscrit/e',
                'required'=>false
            ])
            ->add('passe', CheckboxType::class, ['label' => 'Sorties passées',
                'required'=>false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/Controller/SortiesController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\Lieux;
use App\Entity\Sorties;
use App\Entity\Villes;
use App\Form\AnnulerSortieType;
use App\Form\CreerSortieType;
use App\Form\SortiesType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SortiesController extends Controller
{
    /**
     * @Route("/afficherSortie",name="afficherSortie")
     * @param Request $request
     * @param EntityManagerInterface $em
     */
    public function afficherSortie(Request $request, EntityManagerInterface $em)
    {
        $idSortie = $request->get('id');
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($idSortie);
        return $this->render('sorties/afficher.html.twig', [
            'controller_name' => 'SortiesController',
            'sortie' => $sortie,
        ]);
    }


    /**
     * @Route("/annuler",name="annuler")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function annuler(Request $request, EntityManagerInterface $em)
    {
        $idSortie = $request->get('id');
        dump($idSortie);
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($idSortie);
        $etatRepo = $this->getDoctrine()->getRepository(Etat::class);
        $etatAnnulee = $etatRepo->find(6);
        $annulerSortieForm = $this->createForm(AnnulerSortieType::class, $sortie);
        $annulerSortieForm->handleRequest($request);
        dump($sortie);
        dump($annulerSortieForm->isSubmitted());
        dump($annulerSortieForm->isValid());
        if ($annulerSortieForm->isSubmitted() && $annulerSortieForm->isValid()) {
            dump($idSortie);
            $sortie->setEtat($etatAnnulee);
            $em->persist($sortie);
            $em->flush();
            $this->addFlash('success', 'Votre sortie a bien été annulée');
            return $this->redirectToRoute("accueil");
        }
        return $this->render('sorties/annuler.html.twig', [
            'controller_name' => 'SortiesController',
            'annulerSortie' => $annulerSortieForm->createView(),
            'sortie' => $sortie,
        ]);
    }

    /**
     * @Route("/seDesister",name="seDesister")
     * @param Request $request
     * @param EntityManagerInterface $em
     */
    public function seDesister(Request $request, EntityManagerInterface $em)
    {
        $utilisateur = $this->getUser();
        $idSortie = $request->get('id');
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($idSortie);
        $sortie->removeParticipant($utilisateur);
        $em->persist($sortie);
        $em->flush();
        $this->addFlash('success', 'Vous êtes bien désinscrit de la sortie');
        return $this->redirectToRoute("accueil");
    }

    /**
     * @Route("/sInscrire",name="sInscrire")
     */
    public function sInscrire(Request $request, EntityManagerInterface $em)
    {
        $utilisateur = $this->getUser();
        $idSortie = $request->get('id');
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($idSortie);
        $sortie->addParticipant($utilisateur);
        $em->persist($sortie);
        $em->flush();
        $this->addFlash('success', 'Vous êtes bien inscrit à la sortie');

        return $this->redirectToRoute("accueil");
    }


    /**
     * @Route("/adresseLieu",name="adresseLieu")
     */
    public function getAdresseLieux(Request $request)
    {
        $idLieu = $request->get("lieu");
        dump($idLieu);

        //a revoir
        if ($idLieu == null) {
            $idLieu = 0;
        }

        $lieuxRepo = $this->getDoctrine()->getRepository(Lieux::class);
        $lieux = $lieuxRepo->findAdresseLieu($idLieu);
        dump($lieux);
        $array = [];
        foreach ($lieux as $lieu) {
            dump($lieu->getRue());
            dump($lieu->getLatitude());
            dump($lieu->getLongitude());
            $array[] = [
                'rue' => $lieu->getRue(),
                'latitude' => $lieu->getLatitude(),
                'longitude' => $lieu->getLongitude(),
            ];
        }
        return new JsonResponse($array);
    }


    /**
     * @Route("/lieuxDeVille",name="lieuxDeVille")
     */
    public function getLieux(Request $request)
    {
        $idVille = $request->get("ville");
        dump($idVille);

        $villeRepo = $this->getDoctrine()->getRepository(Villes::class);
        $ville = $villeRepo->find($idVille);
        dump($ville->getCodePostal());
        dump($ville->getNomVille());

        $lieuxRepo = $this->getDoctrine()->getRepository(Lieux::class);
        $lieux = $lieuxRepo->findLieuxByVille($idVille);
        dump($lieux);
        $array = [];
        foreach ($lieux as $lieu) {
            $array[] = [
                'id' => $lieu->getId(),
                'nom' => $lieu->getNomLieu(),
                'codePostal' => $ville->getCodePostal(),
            ];
        }
        return new JsonResponse($array);
    }

    /**
     * @Route("/sorties", name="accueil")
     */
    public function filtreSorties(Request $request)
    {
        $utilisateur = $this->getUser();

        //je récupère toutes les sorties et je les affiche dans un tableau
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sorties = $sortieRepo->findSortieEtat($utilisateur);

        $filtreSortie = $this->createForm(SortiesType::class);
        $filtreSortie->handleRequest($request);

        if ($filtreSortie->isSubmitted() && $filtreSortie->isValid()) {

            $sorties = $sortieRepo->findSortieByRecherche($filtreSortie, $utilisateur);
            return $this->render('sorties/accueil.html.twig', [
                'controller_name' => 'SortiesController',
                'sorties' => $sorties,
                "filtreSortie" => $filtreSortie->createView(),
            ]);
        }
        return $this->render('sorties/accueil.html.twig', [
            'controller_name' => 'SortiesController',
            'sorties' => $sorties,
            "filtreSortie" => $filtreSortie->createView(),
        ]);
    }

    /**
     * @Route("/creerSortie", name="creer")
     */
    public function creerSortie(Request $request, EntityManagerInterface $em)
    {
        $sortie = new Sorties();
        $creerSortieForm = $this->createForm(CreerSortieType::class, $sortie);
        $creerSortieForm->handleRequest($request);

        if ($creerSortieForm->isSubmitted() && $creerSortieForm->isValid()) {
            $utilisateur = $this->getUser();
            $sortie->setOrganisateur($utilisateur);
            $etatRepo = $this->getDoctrine()->getRepository(Etat::class);
            $etatOuverte = $etatRepo->find(2);
//            dump($etatOuverte);
            $sortie->setEtat($etatOuverte);
            $sortie->addParticipant($utilisateur);
            $sortie->setSite($utilisateur->getSite());
//            dump($creerSortieForm);
            $em->persist($sortie);
            $em->flush();
            $this->addFlash('success', 'La sortie a bien été créée');

            return $this->redirectToRoute("accueil");
        }
        return $this->render('sorties/creer.html.twig', [
            'controller_name' => 'SortiesController',
            'creerSortie' => $creerSortieForm->createView(),
        ]);
    }
}

templates/sorties/accueil.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Liste des sorties{% endblock %}


{% block main %}
    <div class="bg">
    <div class="container">
        <div><h6>Bienvenue {{ app.user.login }}</h6></div>
        <div><h6>Nous sommes le {{ "now"|date("d/m/Y") }}</h6></div>
        <div><h5>Filtrer les sorties</h5></div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm">

                {{ form_start(filtreSortie) }}
                <div class="form-group row">
                    {{ form_row(filtreSortie.site) }}
                </div>
                <div class="form-group row">
                    {{ form_row(filtreSortie.nom_sortie) }}
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group row">
                    {{ form_row(filtreSortie.entreDate) }}
                </div>
                <div class="form-group row">
                    {{ form_row(filtreSortie.etDate) }}
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group row">
                    {{ form_row(filtreSortie.organisateur) }}
                </div>
                <div class="form-group row">
                    {{ form_row(filtreSortie.inscrit) }}
                </div>
                <div class="form-group row">
                    {{ form_row(filtreSortie.nonInscrit) }}
                </div>
                <div class="form-group row">
                    {{ form_row(filtreSortie.passe) }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Rechercher</button>
    </div>




    {{ form_end(filtreSortie) }}
    </div>
    <div class="container">
        <table class="table">
            <tr>
                <th>Nom de la sortie :</th>
                <th>Date de la sortie :</th>
                <th>Clôture des inscriptions le :</th>
                <th>Inscrits/places</th>
                <th>Etat</th>
                <th>Inscrit</th>
                <th>Organisateur</th>
                <th>Actions</th>
            </tr>
            {% for sortie in sorties %}

                <tr>
                    <td>
                        {{ sortie.nomSortie }}
                    </td>
                    <td>
                        {{ sortie.datedebut|date('d-m-Y G:i') }}
                    </td>
                    <td>
                        {{ sortie.datecloture|date('d-m-Y G:i') }}
                    </td>
                    <td>
                        {{ sortie.participants.snapshot|length }}/{{ sortie.nbinscriptionsmax }}
                    </td>
                    <td>
                        {{ sortie.etat.libelle }}
                    </td>
                    <td>
                        {% set participe = false %}
                        {% for participant in sortie.participants.snapshot %}
                            {% if app.user.id == participant.id %}
                                <img src="{{ asset('img/valide.png') }}" alt="">
                                {% set participe = true %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{{ path('afficher_profil',{'id':sortie.organisateur.getId}) }}">{{ sortie.organisateur.login }}</a>

                    </td>
                    <td>
                        {% set maSortie = false %}
                        {% if app.user.id == sortie.organisateur.id %}
                            {% set maSortie = true %}
                        {% endif %}
                        {% if sortie.etat.id != 1 %}
                            <a href="{{ path('afficherSortie', {'id':sortie.id}) }}">Afficher</a>
                        {% endif %}
                        {% if sortie.etat.id == 2 and participe == true or sortie.etat.id == 3 and participe == true %}
                            <a href="{{ path('seDesister', {'id':sortie.id}) }}">Se désister</a>
                        {% endif %}
                        {% if sortie.etat.id == 2 and sortie.participants.snapshot|length < sortie.nbinscriptionsmax and participe != true %}
                            <a href="{{ path('sInscrire', {'id':sortie.id}) }}">S'inscrire</a>
                        {% endif %}
                        {% if sortie.etat.id == 1 and maSortie == true %}
                            <a href="#">Modifier</a>
                        {% endif %}
                        {% if sortie.etat.id == 1 and maSortie == true %}
                            <a href="#">Publier</a>
                        {% endif %}
                        {% if sortie.etat.id == 2 and maSortie == true %}
                            <a href="{{ path('annuler', {'id':sortie.id}) }}">Annuler</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="container">
        <h2><a href="{{ path('creer') }}" class="btn btn-primary btn-lg btn-block">Créer une sortie</a></h2>
    </div>
    </div>
{% endblock %}

templates/sorties/afficher.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Détails d'une sortie{% endblock %}

{% block main %}
    <div class="bg">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div>
                        <h5>Détails d'une sortie</h5>
                    </div>
                    <div>
                        Nom de la sortie : {{ sortie.nomSortie }}
                    </div>
                    <div>
                        Date de la sortie : {{ sortie.datedebut|date ("d/m/Y à H:i") }}
                    </div>
                    <div>
                        Date limite d'inscription : {{ sortie.datecloture|date ("d/m/y") }}
                    </div>
                    <div>
                        Nombre de places : {{ sortie.nbinscriptionsmax }}
                    </div>
                    <div>
                        Durée : {{ sortie.duree }} minutes
                    </div>
                    <div>
                        Description et infos : {{ sortie.descriptionsinfos }}
                    </div>
                </div>
                <div class="col-sm">
                    <div>
                        Ville organisatrice : {{ sortie.site.getNomSite }}
                    </div>
                    <div>
                        Ville : {{ sortie.lieu.getVille.getNomVille }}
                    </div>
                    <div>
                        Lieu : {{ sortie.lieu.getNomLieu }}
                    </div>
                    <div>
                        Rue : {{ sortie.lieu.getRue }}
                    </div>
                    <div>
                        Code postal : {{ sortie.lieu.getVille.getCodePostal }}
                    </div>
                    <div>
                        Latitude : {{ sortie.lieu.getLatitude }}
                    </div>
                    <div>
                        Longitude : {{ sortie.lieu.getLongitude }}
                    </div>
                </div>
            </div>
        </div>


        <div class="container">


            <div>
                Liste des participants inscrits :
            </div>
            <div>
                <table class="table">
                    <tr>
                        <th>Pseudo</th>
                        <th>Nom</th>
                    </tr>

                    {% for participant in sortie.participants %}
                        <tr>
                            <td>{{ participant.getLogin }}</td>
                            <td>{{ participant.getPrenom }} {{ participant.getNom }}</td>
                        </tr>
                    {% endfor %}

                </table>
                <a href="{{ path('accueil') }}" type="button" class="btn btn-primary btn-lg btn-block">Annuler</a>
            </div>
        </div>

    </div>
{% endblock %}

templates/sorties/annuler.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Annuler une sortie{% endblock %}

{% block main %}
    <div class="bg">
        <div class="container">
            <div>
                <h5>Annuler une sortie</h5>
            </div>
            <div>
                Nom de la sortie : {{ sortie.nomSortie }}
            </div>
            <div>
                Date de la sortie : {{ sortie.datedebut|date ("d/m/Y") }}
            </div>
            <div>
                Ville organisatrice : {{ sortie.site.getNomSite }}
            </div>
            <div>
                Lieu
                : {{ sortie.lieu.getNomLieu }} {{ sortie.lieu.getRue }} {{ sortie.lieu.getVille.getNomVille }} {{ sortie.lieu.getVille.getCodePostal }}
            </div>

            {{ form_start(annulerSortie) }}
            {{ form_row(annulerSortie.descriptionsinfos) }}
            <button type="submit" class="btn btn-primary">Enregistrer</button>

            <a href="{{ path('accueil') }}" type="button" class="btn btn-primary">Annuler</a>
            {{ form_end(annulerSortie) }}
        </div>
    </div>
{% endblock %}

templates/sorties/creer.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Créer une nouvelle sortie{% endblock %}

{% block main %}
    <div class="bg">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div><h5>Créer une sortie</h5></div>

                    {{ form_start(creerSortie) }}
                    <div class="form-group row">
                        {{ form_row(creerSortie.nom_sortie) }}
                    </div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.datedebut) }}
                    </div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.datecloture) }}
                    </div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.nbinscriptionsmax) }}
                    </div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.duree) }}
                    </div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.descriptionsinfos) }}
                    </div>
                </div>
                <div class="col-sm">
                    <div><h5>Ville organisatrice</h5></div>
                    <div class="form-group row">
                        {{ form_row(creerSortie.ville) }}
                    </div>
                    {#        <label>Lieu : </label>#}
                    <div class="form-group row">

                        {{ form_row(creerSortie.lieu) }}
                        {#            <select name="lieux" id="lieux"></select>#}
                    </div>
                    <div class="form-group row">Rue :</div>
                    <div class="form-group row" id="rue">
                    </div>
                    <div class="form-group row">Code postal :</div>
                    <div class="form-group row" id="codePostal">
                    </div>
                    <div class="form-group row">Latitude :</div>
                    <div class="form-group row" id="latitude">
                    </div>
                    <div class="form-group row">Longitude :</div>
                    <div class="form-group row" id="longitude">
                    </div>
                </div>
            </div>
        </div>


        <div class="container">


            <button type="submit" class="btn btn-primary btn-lg btn-block">Créer une sortie</button>
            <a href="{{ path('accueil') }}" type="button" class="btn btn-primary btn-lg btn-block">Annuler</a>
            {{ form_end(creerSortie) }}
        </div>
    </div>
    <script src="jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#creer_sortie_ville').change();
        });
        $('#creer_sortie_ville').change(function (e) {
            var ville = $('#creer_sortie_ville').val();
            console.log(ville);
            $.ajax({
                url: "{{ path('lieuxDeVille') }}?ville=" + ville,
                cache: false
            })
                .done(function (lieux) {
                    $('#creer_sortie_lieu').empty();
                    // $('#lieux').empty();
                    $('#codePostal').empty();
                    $('#codePostal').append($('<div>' + lieux[0].codePostal + '</div>'));
                    lieux.forEach(function (lieu) {
                        console.log(lieu.nom);
                        $('#creer_sortie_lieu').append($('<option value="' + lieu.id + '">' + lieu.nom + '</option>'));
                        // $('#lieux').append($('<option value="' + lieu.id + '">' + lieu.nom + '</option>'));
                    });
                    //on actualise les lieux en changeant de ville en appelant la fonction de lieu
                    $('#creer_sortie_lieu').change();
                    // $('#lieux').change();
                });
            e.preventDefault();
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#creer_sortie_lieu').change();
            // $('#lieux').change();
        });
        $('#creer_sortie_lieu').change(function (e) {
            // $('#lieux').change(function (e) {
            var lieu = $('#creer_sortie_lieu').val();
            // var lieu = $('#lieux').val();
            console.log(lieu);
            $.ajax({
                url: "{{ path('adresseLieu') }}?lieu=" + lieu,
                cache: false
            })
                .done(function (lieux) {
                    $('#rue').empty();
                    $('#latitude').empty();
                    $('#longitude').empty();
                    lieux.forEach(function (lieu) {
                        $('#rue').append($('<div>' + lieu.rue + '</div>'));
                        $('#latitude').append($('<div>' + lieu.latitude + '</div>'));
                        $('#longitude').append($('<div>' + lieu.longitude + '</div>'));
                    });
                });
            e.preventDefault();
        });
    </script>


{% endblock %}